from main import Theorist

theorist = Theorist()
theorist.theoretical_analysis("motion0")
theorist.theoretical_analysis("motion0")
theorist.theoretical_analysis("motion0")
theorist.theoretical_analysis("motion0")
theorist.specific["motion0"].print_conclusion()
print('-'*20)
theorist.theoretical_analysis("motion")
theorist.theoretical_analysis("motion")
theorist.theoretical_analysis("motion")
theorist.theoretical_analysis("motion")
theorist.specific["motion"].print_conclusion()
theorist.theoretical_analysis("oscillation")
theorist.theoretical_analysis("oscillation")
theorist.theoretical_analysis("oscillation")
theorist.theoretical_analysis("oscillation")
theorist.specific["oscillation"].print_conclusion()